# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main


pool:
  vmImage: ubuntu-latest


variables:

  azureServiceConnection: Azure-management-group-service-connection

  managementGroupId: mg-governance

  subscriptionId: 77b4751e-5e24-4172-9fd1-d9c63cd63fb8

  blueprintName: azure_security_compliance_blueprint

  blueprintVersion: $(Build.BuildId)

  assignmentName: security-compliance-assignment

  assignmentLocation: canadacentral

  blueprintPath: blueprints/azure_security_compliance_blueprint



stages:


# ======================================================
# Stage 1 - Validate Blueprint Files
# ======================================================

- stage: Validate

  displayName: Validate Blueprint

  jobs:

  - job: ValidateFiles

    steps:


    - checkout: self


    - bash: |

        echo "Checking blueprint files"


        test -f $(blueprintPath)/blueprint.json || exit 1


        test -f $(blueprintPath)/parameters/parameters.json || exit 1


        echo "Validation successful"


      displayName: Validate Files





# ======================================================
# Stage 2 - Create Blueprint Definition
# ======================================================


- stage: CreateBlueprint

  dependsOn: Validate

  jobs:


  - job: Create


    steps:


    - task: AzureCLI@2

      displayName: Create Blueprint Definition

      inputs:

        azureSubscription: $(azureServiceConnection)

        scriptType: bash

        scriptLocation: inlineScript


        inlineScript: |


          set -e


          echo "Creating Blueprint"


          BLUEPRINT_ID="/providers/Microsoft.Management/managementGroups/$(managementGroupId)/providers/Microsoft.Blueprint/blueprints/$(blueprintName)"


          BODY=$(cat $(blueprintPath)/blueprint.json)


          az rest \

          --method PUT \

          --url "https://management.azure.com$BLUEPRINT_ID?api-version=2018-11-01-preview" \

          --body "$BODY"



          echo "Blueprint created"





# ======================================================
# Stage 3 - Create Blueprint Artifacts
# ======================================================


- stage: CreateArtifacts

  dependsOn: CreateBlueprint


  jobs:


  - job: Artifacts


    steps:


    - task: AzureCLI@2

      displayName: Create Blueprint Artifacts


      inputs:


        azureSubscription: $(azureServiceConnection)

        scriptType: bash

        scriptLocation: inlineScript


        inlineScript: |


          set -e


          echo "Creating artifacts"


          for file in $(blueprintPath)/artifacts/*.json

          do


            NAME=$(basename $file .json)


            echo "Creating artifact $NAME"



            ARTIFACT_ID="/providers/Microsoft.Management/managementGroups/$(managementGroupId)/providers/Microsoft.Blueprint/blueprints/$(blueprintName)/artifacts/$NAME"



            BODY=$(cat $file)



            az rest \

            --method PUT \

            --url "https://management.azure.com$ARTIFACT_ID?api-version=2018-11-01-preview" \

            --body "$BODY"



          done


          echo "Artifacts created"





# ======================================================
# Stage 4 - Publish Blueprint
# ======================================================


- stage: Publish


  dependsOn: CreateArtifacts


  jobs:


  - job: PublishBlueprint


    steps:


    - task: AzureCLI@2


      displayName: Publish Blueprint Version


      inputs:


        azureSubscription: $(azureServiceConnection)

        scriptType: bash

        scriptLocation: inlineScript


        inlineScript: |


          set -e


          echo "Publishing Blueprint"


          PUBLISH_URL="/providers/Microsoft.Management/managementGroups/$(managementGroupId)/providers/Microsoft.Blueprint/blueprints/$(blueprintName)/versions/$(blueprintVersion)"


          az rest \

          --method PUT \

          --url "https://management.azure.com$PUBLISH_URL?api-version=2018-11-01-preview" \

          --body "{}"


          echo "Published"





# ======================================================
# Stage 5 - Assign Blueprint
# ======================================================


- stage: Assign


  dependsOn: Publish


  jobs:


  - job: Assignment


    steps:


    - task: AzureCLI@2


      displayName: Assign Blueprint


      inputs:


        azureSubscription: $(azureServiceConnection)

        scriptType: bash

        scriptLocation: inlineScript



        inlineScript: |


          set -e


          echo "Assigning Blueprint"


          ASSIGNMENT_ID="/subscriptions/$(subscriptionId)/providers/Microsoft.Blueprint/blueprintAssignments/$(assignmentName)"


          BODY=$(cat $(blueprintPath)/parameters/parameters.json)



          az rest \

          --method PUT \

          --url "https://management.azure.com$ASSIGNMENT_ID?api-version=2018-11-01-preview" \

          --body "$BODY"



          echo "Assignment completed"





# ======================================================
# Stage 6 - Verify Compliance
# ======================================================


- stage: Verify


  dependsOn: Assign


  jobs:


  - job: Compliance


    steps:


    - task: AzureCLI@2


      displayName: Policy Compliance Check


      inputs:


        azureSubscription: $(azureServiceConnection)

        scriptType: bash

        scriptLocation: inlineScript


        inlineScript: |


          az policy state summarize \
          --subscription $(subscriptionId)